[Unit]
After=pipewire.socket pipewire-pulse.socket wireplumber.service network-online.target
Wants=pipewire.socket pipewire-pulse.socket wireplumber.service

[Service]
Restart=on-failure
RestartSec=5
ExecStartPre=/bin/sleep 5
ExecStart=
ExecStart=/usr/bin/shairport-sync --log-to-syslog -c %h/.config/shairport-sync.conf
