hl.on("hyprland.start", function ()
    hl.exec_cmd("qs -c $qsConfig")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP") -- Some fix idk
    hl.exec_cmd("wl-paste --type text --watch bash -c 'cliphist store && qs -c $qsConfig ipc call cliphistService update'")
    hl.exec_cmd("wl-paste --type image --watch bash -c 'cliphist store && qs -c $qsConfig ipc call cliphistService update'")
    hl.exec_cmd("playerctld daemon")
    hl.exec_cmd("localsend --hidden")
    hl.exec_cmd("sleep 5 && touch ~/.config/hypr/custom/execs.conf")
    hl.exec_cmd("sleep 5 && hyprpm reload -n")
    hl.exec_cmd("hyprctl setcursor macOS-hypr 24")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal &")
    hl.exec_cmd("sleep 2 && /usr/lib/xdg-desktop-portal-gtk &")
    -- hl.exec_cmd("hyprmoncfgd")
    -- hl.exec_cmd("quickshell -p ~/.config/quickshell/qs-hyprview")
    hl.exec_cmd("STEAM_FRAME_FORCE_CLOSE=1 steam -silent")
    hl.exec_cmd("discord --start-minimized")
    hl.exec_cmd("sleep 10 && qbittorrent")
    -- hl.exec_cmd("claude-desktop & sleep 3 && hyprctl dispatch 'hl.dsp.window.close({ window = \"class:Claude\" })'")
    hl.exec_cmd("WAYLAND_DISPLAY=wayland-1 XDG_RUNTIME_DIR=/run/user/1000 wayvnc --render-cursor  0.0.0.0 5900")
    hl.exec_cmd("hyprlock")
end)
