background            #1A1A1A

color0                #1A1A1A
color1                #FF553D
color2                #FFBF85
color3                #FFE0D0
color4                #B8AC66
color5                #F08E94
color6                #F5C06E
color7                #EFD2C4
color8                #CBB4AA
color9                #FFAB9C
color10               #FFFCFF
color11               #FFFFFF
color12               #F1DAAB
color13               #FFCECD
color14               #FFF9F6
color15               #DAE4E6

cursor                #EFD2C4

foreground            #EFD2C4

selection_background  #FFDAD3
selection_foreground  #5D3F39

# Override obscure colors for starship prompt (these are greys at the end)
color255              #FFB4A5
color254              #7D2C1C
color253              #E7BDB4
color252              #5D3F39
color251              #DCC48C
color250              #A38F5B
color249              #FFB4AB
color248              #93000A

color232              #5F1608
color233              #FFDAD3
color234              #442A24
color235              #FFDAD3
color236              #3D2F04
color237              #000000
color238              #690005
color239              #FFDAD6
color240              #5F1608 // Somehow 232 doesn't work so i gotta use another number

# Some stuff should specifically use the colors in the middle so they look acceptable in both unthemed light/dark
color243              #FFB4A5
color244              #FFB4AB
color245              #474747
